### ISSUE TITLE
Project 5: Application deploy

### ISSUE THREAD

**Issue by MarcoOquendoC** [MarcoOquendoC/Portfolio#6]
# Project 5: Application deploy.

## These features are in the main branch:

- Deploy website using GitHub Pages.
- Check the online version and make sure that the page works properly.
- Update the README file to include a link to the online version.
- Update the README of my repository to include a link to the online version.
- Open an issue with a link to the [online version](https://marcooquendoc.github.io/Portfolio/).

**Comment by tresorsawasawa** [comment]
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @MarcoOquendoC 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## NOTICE
### Kindly make sure for your next projects to provide a `Pull Request` link for requesting a review instead of an `issues` link. 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoOquendoC** [comment]
### Thanks for your kindness dear @tresorsawasawa. 
I was worried you would take me back to the previous merge due to my error.


![giphy](https://user-images.githubusercontent.com/104022866/178371851-5c34cc13-5504-44b2-830a-ef2004a1750f.gif)
